# Generated by Django 5.2.16 on 2026-09-16 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_classcategory_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classvideo',
            name='class_category',
        ),
        migrations.DeleteModel(
            name='ClassGalleryImage',
        ),
        migrations.DeleteModel(
            name='ClassVideo',
        ),
    ]
