# Generated by Django 5.2.16 on 2026-09-28 08:29

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_classvideo_class_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('file', models.FileField(blank=True, null=True, upload_to='academics/main/')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='academics/Academics/')),
            ],
        ),
        migrations.CreateModel(
            name='SubAcademics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('file', models.FileField(blank=True, null=True, upload_to='academics/sub/')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='academics/SubAcademics/')),
                ('academics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subacademics', to='academics.academics')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('file', models.FileField(blank=True, null=True, upload_to='academics/main/')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='academics/AcademicsItem/')),
                ('subacademics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='academics.subacademics')),
            ],
        ),
    ]
