# Generated by Django 5.2.16 on 2026-08-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloatingButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('is_active', models.BooleanField(default=True)),
                ('button_type', models.CharField(choices=[('apply_now', 'Apply Now'), ('whatsapp', 'WhatsApp'), ('call_now', 'Call Now'), ('custom', 'Custom')], max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('link_or_number', models.CharField(help_text='URL for Apply Now/Custom, phone number for Call Now, WhatsApp number (with country code, digits only) for WhatsApp.', max_length=255)),
                ('icon', models.CharField(blank=True, help_text="Optional icon name/class used by the frontend, e.g. 'phone', 'whatsapp'.", max_length=50)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Notification Recipient',
                'verbose_name_plural': 'Notification Recipients (Popup Automailer)',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Little Star Public School', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='core/logo/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='core/favicon/')),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('footer_about', models.TextField(blank=True)),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
                ('default_meta_title', models.CharField(blank=True, max_length=200)),
                ('default_meta_description', models.TextField(blank=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
