# Generated by Django 5.2.16 on 2026-08-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionPopupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('heading', models.CharField(default='Admissions Open – Apply Now', max_length=200)),
                ('subtext', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sliders/popup/')),
                ('show_after_seconds', models.PositiveIntegerField(default=2, help_text='Delay before the popup appears on first visit.')),
            ],
            options={
                'verbose_name': 'Admission Popup Settings',
                'verbose_name_plural': 'Admission Popup Settings',
            },
        ),
        migrations.CreateModel(
            name='BannerSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='sliders/banners/')),
                ('cta_type', models.CharField(choices=[('apply_now', 'Apply Now'), ('book_visit', 'Book a School Visit'), ('contact_us', 'Contact Us'), ('custom', 'Custom')], default='apply_now', max_length=20)),
                ('cta_text', models.CharField(blank=True, max_length=50)),
                ('cta_link', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
