# Generated by Django 5.2.16 on 2026-08-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerslide',
            name='image',
        ),
        migrations.AddField(
            model_name='bannerslide',
            name='file',
            field=models.FileField(default=1, upload_to='sliders/banners/'),
            preserve_default=False,
        ),
    ]
