# Generated by Django 5.2.16 on 2026-08-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0002_remove_bannerslide_image_bannerslide_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopUpWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sliders/popup/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
