# Generated by Django 5.2.16 on 2026-09-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0003_popupwindow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerslide',
            name='cta_type',
            field=models.CharField(choices=[('n/a', 'N/A'), ('apply_now', 'Apply Now'), ('book_visit', 'Book a School Visit'), ('contact_us', 'Contact Us'), ('custom', 'Custom')], default='n/a', max_length=20),
        ),
        migrations.AlterField(
            model_name='bannerslide',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
