# Generated by Django 5.2.16 on 2026-08-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('smart_classroom', 'Smart Classrooms'), ('computer_lab', 'Computer Lab'), ('library', 'Library'), ('sports', 'Sports Facilities'), ('medical', 'Medical Room'), ('transport', 'Transportation'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='infrastructure/')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
