# Generated by Django 5.2.16 on 2026-08-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('history', models.TextField(blank=True)),
                ('infrastructure_summary', models.TextField(blank=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='pages/about/')),
            ],
            options={
                'verbose_name': 'About Us Page',
                'verbose_name_plural': 'About Us Page',
            },
        ),
        migrations.CreateModel(
            name='ChairmanMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Chairman', max_length=150)),
                ('designation', models.CharField(default='Chairman', max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pages/chairman/')),
                ('short_message', models.TextField(help_text='Short excerpt shown on the Home page.')),
                ('full_message', models.TextField(help_text='Full message shown on the About Us page.')),
            ],
            options={
                'verbose_name': "Chairman's Message",
                'verbose_name_plural': "Chairman's Message",
            },
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_title', models.CharField(default='Welcome to Little Star Public School', max_length=200)),
                ('welcome_text', models.TextField(blank=True)),
                ('welcome_image', models.ImageField(blank=True, null=True, upload_to='pages/home/')),
            ],
            options={
                'verbose_name': 'Home Page - Welcome Message',
                'verbose_name_plural': 'Home Page - Welcome Message',
            },
        ),
        migrations.CreateModel(
            name='PrincipalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Principal', max_length=150)),
                ('designation', models.CharField(default='Principal', max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pages/principal/')),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': "Principal's Message",
                'verbose_name_plural': "Principal's Message",
            },
        ),
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(help_text='Internal path (e.g. /admissions) or full URL.', max_length=255)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name/class for the frontend.', max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
