# Generated by Django 5.2.16 on 2026-08-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecontent',
            name='welcome_image',
            field=models.FileField(blank=True, null=True, upload_to='pages/home/'),
        ),
    ]
