# Generated by Django 5.2.16 on 2026-08-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_homecontent_welcome_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='principalmessage',
            name='message',
        ),
        migrations.AddField(
            model_name='principalmessage',
            name='full_message',
            field=models.TextField(default=1, help_text='Full message shown on the About Us page.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='principalmessage',
            name='short_message',
            field=models.TextField(default=1, help_text='Short excerpt shown on the Home page.'),
            preserve_default=False,
        ),
    ]
