# Generated by Django 5.2.16 on 2026-09-16 10:02

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_principalmessage_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='history',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='infrastructure_summary',
        ),
        migrations.AddField(
            model_name='chairmanmessage',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='principalmessage',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='introduction',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='introduction'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='mission',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='introduction'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='vision',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='introduction'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('is_active', models.BooleanField(default=True)),
                ('year', models.CharField(max_length=4)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.aboutus')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
