# Generated by Django 5.2.16 on 2026-09-16 10:13

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_aboutus_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='mission',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='mission'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='vision',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='vision'),
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/Infrastructure/')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.aboutus')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
