# Generated by Django 5.2.16 on 2026-09-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_aboutus_mission_alter_aboutus_vision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSectionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('about', 'About Us'), ('academics', 'Academics'), ('admissions', 'Admissions'), ('gallery', 'Gallery'), ('news_events', 'News & Events'), ('contact', 'Contact Us')], max_length=30, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/cards/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
