# Generated by Django 5.2.16 on 2026-09-28 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_homesectioncard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homesectioncard',
            name='is_active',
        ),
    ]
