# Generated by Django 5.2.16 on 2026-10-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_homesectioncard_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesectioncard',
            name='section',
            field=models.CharField(choices=[('about', 'About Us'), ('careers', 'Careers'), ('admissions', 'Admissions'), ('gallery', 'Gallery'), ('news_events', 'News & Events'), ('contact', 'Contact Us')], max_length=30, unique=True),
        ),
    ]
