# Generated by Django 5.2.16 on 2026-08-28 09:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionenquiry',
            name='email',
        ),
        migrations.RemoveField(
            model_name='admissionenquiry',
            name='source',
        ),
        migrations.RemoveField(
            model_name='admissionenquiry',
            name='status',
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='interested_in',
            field=models.CharField(blank=True, choices=[('admission_enquiry', 'Admission Enquiry'), ('school_visit', 'School Visit'), ('both', 'Both')], default='admission_enquiry', max_length=20, verbose_name='I am Interested In'),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='preferred_visit_date',
            field=models.DateField(blank=True, help_text="Required only when 'School Visit' or 'Both' is selected.", null=True, verbose_name='Preferred Visit Date'),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='student_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Child Age'),
        ),
        migrations.AlterField(
            model_name='admissionenquiry',
            name='class_applying_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_enquiries', to='academics.classcategory', verbose_name='Admission Required For Class'),
        ),
        migrations.AlterField(
            model_name='admissionenquiry',
            name='parent_name',
            field=models.CharField(max_length=150, verbose_name='Parent/Guardian Name'),
        ),
        migrations.AlterField(
            model_name='admissionenquiry',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number (optionally prefixed with +91).', regex='^\\+?91?\\d{10}$')], verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='admissionenquiry',
            name='student_name',
            field=models.CharField(blank=True, max_length=150, verbose_name="Child's Name"),
        ),
    ]
