# Generated by Django 5.2.16 on 2026-08-29 16:53

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_remove_admissionenquiry_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requireddocument',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
    ]
