# Generated by Django 5.2.16 on 2026-08-30 07:50

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_alter_requireddocument_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionprocessstep',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
    ]
