# Generated by Django 5.2.16 on 2026-09-28 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_alter_admissionprocessstep_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionformdownload',
            options={'verbose_name': 'Download Form', 'verbose_name_plural': 'Download Forms'},
        ),
    ]
