# Generated by Django 5.2.16 on 2026-08-28 09:52

import apps.careers.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Job Position',
                'verbose_name_plural': 'Job Positions',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('mobile_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number (optionally prefixed with +91).', regex='^\\+?91?\\d{10}$')], verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('qualification_experience', models.CharField(max_length=500, verbose_name='Qualification & Experience')),
                ('resume', models.FileField(upload_to='careers/resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), apps.careers.models.validate_resume_size], verbose_name='Attach CV/Resume')),
                ('status', models.CharField(choices=[('new', 'New'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview Scheduled'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='careers.jobposition', verbose_name='Apply for Position')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
