# Generated by Django 5.2.16 on 2026-08-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='qualification_experience',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='experience',
            field=models.CharField(default=1, max_length=500, verbose_name='Experience'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='qualification',
            field=models.CharField(default=1, max_length=500, verbose_name='Qualification'),
            preserve_default=False,
        ),
    ]
