# Generated by Django 5.2.16 on 2026-08-29 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_remove_jobapplication_qualification_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='qualification',
        ),
    ]
